###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/2

###
POST http://localhost:3000/products
content-type: application/json

{
  "name": "spoon",
  "price": 3, 
  "description": "for shoveling food into your mouth"
}

###
PATCH http://localhost:3000/products/6
content-type: application/json

{
  "name": "knife",
  "price": 4, 
  "description": "for cutting food"
}

###
DELETE http://localhost:3000/products/7

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Katrina",
  "email": "Katrina@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "ben@test.com",
  "password": "password"
}

### order create
POST http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDgwNzYxNjl9.hQVYjvEJBPaHHL30e5wm2jFMbFz3RPDke-ZIu8iWZ4I
Content-Type: application/json

{
  "product_id": 2,
  "quantity": 4
}

###
GET http://localhost:3000/orders